## 이상치를 찾아라(소수점 나이)
### 주어진 데이터에서 이상치(소수점 나이)를 찾고 올림, 내림, 버림(절사)했을때 3가지 모두 이상치 'age' 평균을 구한 다음 모두 더하여 출력하시오

- 데이터셋 : basic1.csv
- 오른쪽 상단 copy&edit 클릭 -> 예상문제 풀이 시작
- 강의 영상 : https://youtu.be/c3Fr9G-ZYdw

In [1]:
# 라이브러리 및 데이터 불러오기
import pandas as pd

data = pd.read_csv("/kaggle/input/bigdatacertificationkr/basic1.csv")

In [3]:
data.head()

     id   age city    f1  f2   f3    f4         f5
0  id01   2.0   서울   NaN   0  NaN  ENFJ  91.297791
1  id02   9.0   서울  70.0   1  NaN  ENFJ  60.339826
2  id03  27.0   서울  61.0   1  NaN  ISTJ  17.252986
3  id04  75.0   서울   NaN   2  NaN  INFP  52.667078
4  id05  24.0   서울  85.0   2  NaN  ISFJ  29.269869

In [8]:
# 소수점 데이터 찾기
import numpy as np

float_data = data[data['age'] != np.floor(data['age'])]

In [9]:
# 이상치를 포함한 데이터 올림, 내림, 버림의 평균값 

t1 = np.ceil(data['age'].mean())
t2 = np.floor(data['age'].mean())
t3 = np.trunc(data['age'].mean())

print(t1,t2,t3)

print("="*10)

print((t1+t2+t3)/3)

51.0 50.0 50.0
==========
50.333333333333336

In [ ]:
# 평균값 더한 다음 출력

## Hint
- import numpy as np
- 올림: np.ceil()
- 내림: np.floor()
- 버림: np.trunc()

### 쉬어가기 : 내림과 버림의 차이는??
- 양수에서는 같지만 음수에서는 -5.5에서 내림을 하면 -6, 버림을하면 -5가 된다.

## 풀이

In [ ]:
# 라이브러리 및 데이터 불러오기
import pandas as pd
import numpy as np

df = pd.read_csv('../input/bigdatacertificationkr/basic1.csv')
df.head()

In [ ]:
# 소수점 데이터 찾기
df = df[(df['age']-np.floor(df['age']))!= 0]
df

In [ ]:
# 이상치를 포함한 데이터 올림, 내림, 버림의 평균값 

# 올림
m_ceil = np.ceil(df['age']).mean()

# 내림
m_floor = np.floor(df['age']).mean()

# 버림
m_trunc = np.trunc(df['age']).mean()

m_ceil, m_floor, m_trunc

In [ ]:
# 평균값 더한 다음 출력
print(m_ceil + m_floor + m_trunc)